apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
    resources:
      limits:
        memory: "1024Mi"
        cpu: "800m"
      requests:
        memory: "256Mi"
        cpu: "500m"
