apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"